import type { Metadata } from 'next';
import LegalPage, { LegalSection } from '@/components/LegalPage';
import { CONTACT, LAST_UPDATED } from '@/lib/legal';

export const metadata: Metadata = {
  title: 'AI Transparency and Disclaimer Notice',
  description:
    'Which parts of CareerBridge Way are AI and which are not, what AI-generated reports get wrong, and why none of it decides anything about you.',
};

/**
 * The document with the highest chance of being read, so the failure modes go
 * near the top rather than in a disclaimer at the bottom.
 *
 * The honest framing matters here: half this product genuinely is a language
 * model and half genuinely is not, and "AI-powered" is used widely enough to
 * mean "we did some arithmetic" that saying which is which is worth a page.
 */
export default function AiNoticePage() {
  return (
    <LegalPage
      title="AI Transparency and Disclaimer Notice"
      lastUpdated={LAST_UPDATED.aiNotice}
      intro={
        <>
          <p>
            Part of this service is artificial intelligence and part of it is not. The career
            scores come from a fixed formula that does not learn. The written report is
            generated by an AI model,{' '}
            <strong className="text-white">no human checks it before you see it</strong>, and
            it can be confidently wrong about jobs, pay, qualifications and entry routes.
          </p>
          <p>
            It is information to think about. It is not careers advice, it is not a
            prediction, and it does not decide anything about you.
          </p>
        </>
      }
    >
      <LegalSection id="which-parts" title="Which parts are AI, and which are not">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[34rem] border-collapse text-sm">
            <thead>
              <tr className="border-b border-white/20 text-left text-xs uppercase tracking-wider text-gray-400">
                <th className="py-2 pr-4 font-medium">Part</th>
                <th className="py-2 pr-4 font-medium">AI?</th>
                <th className="py-2 font-medium">What it actually is</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-white/10 align-top">
                <td className="py-3 pr-4 font-medium text-white">The questionnaire</td>
                <td className="py-3 pr-4 text-gray-300">No</td>
                <td className="py-3 text-gray-300">
                  A fixed set of questions. Everyone sees the same ones, in the same order.
                </td>
              </tr>
              <tr className="border-b border-white/10 align-top">
                <td className="py-3 pr-4 font-medium text-white">Your cluster scores</td>
                <td className="py-3 pr-4 text-gray-300">No</td>
                <td className="py-3 text-gray-300">
                  A fixed, rule-based calculation. Each answer carries a predetermined weight
                  and the totals are arithmetic. It does not learn, does not adapt, and does
                  not change based on what anyone else answered. The same answers produce the
                  same scores every time.
                </td>
              </tr>
              <tr className="border-b border-white/10 align-top">
                <td className="py-3 pr-4 font-medium text-white">Your written report</td>
                <td className="py-3 pr-4 font-medium text-indigo-300">Yes</td>
                <td className="py-3 text-gray-300">
                  A large language model, provided by OpenAI, writes the text from your
                  answers and your scores. This is generative AI, with everything that
                  implies.
                </td>
              </tr>
              <tr className="border-b border-white/10 align-top">
                <td className="py-3 pr-4 font-medium text-white">The follow-up roadmap</td>
                <td className="py-3 pr-4 font-medium text-indigo-300">Yes</td>
                <td className="py-3 text-gray-300">
                  The same, from your follow-up answers.
                </td>
              </tr>
              <tr className="border-b border-white/10 align-top">
                <td className="py-3 pr-4 font-medium text-white">Distress screening</td>
                <td className="py-3 pr-4 text-gray-300">No</td>
                <td className="py-3 text-gray-300">
                  A fixed list of phrases, matched literally. See below.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </LegalSection>

      <LegalSection id="what-it-gets" title="What the AI receives">
        <p>
          When you ask for a report, we send the model{' '}
          <strong className="text-white">
            the relevant parts of your answers, including free text, and your calculated
            scores.
          </strong>
        </p>
        <p>
          We do <strong className="text-white">not</strong> send your email address, your
          name, your payment details, your account identifier, your IP address, or your
          history of previous reports.
        </p>
        <p>
          Your answers pass through a sanitiser first, which strips content that could be
          used to manipulate the model. That is a security measure.{' '}
          <strong className="text-white">
            Do not rely on it to remove personal information
          </strong>{' '}
          &mdash; it is not designed for that and will not catch everything.
        </p>
        <p>
          Your answers are not used to train AI models, ours or OpenAI&rsquo;s. Our{' '}
          <a className="text-indigo-300 underline" href="/privacy#ai">
            Privacy Policy
          </a>{' '}
          covers the contractual position and where the processing happens.
        </p>
      </LegalSection>

      <LegalSection id="failures" title="What AI-generated reports get wrong">
        <div className="rounded-lg border border-amber-400/30 bg-amber-400/5 p-4">
          <p className="text-sm text-amber-100">
            <strong className="font-semibold">This is the section to read.</strong> Everything
            below is an ordinary, known failure of the technology, not a rare fault. Expect
            some of it in your report.
          </p>
        </div>
        <ul className="ml-5 flex list-disc flex-col gap-3">
          <li>
            <strong className="text-white">It invents things.</strong> Language models produce
            text that reads convincingly whether or not it is true. A report can state a
            salary, a qualification, an entry requirement, a professional body or a course
            that does not exist &mdash; in exactly the same confident tone as the parts that
            are correct. You cannot tell them apart by reading.
          </li>
          <li>
            <strong className="text-white">It is out of date.</strong> The model was trained
            on information up to a point in the past and has no live connection to the labour
            market. Salaries, entry requirements, apprenticeship routes, visa rules and
            funding all change, and it will not know.
          </li>
          <li>
            <strong className="text-white">It does not know your local job market</strong>{' '}
            &mdash; where you live, what employers are near you, or what is being hired for
            in your area.
          </li>
          <li>
            <strong className="text-white">
              It knows nothing about you beyond what you typed.
            </strong>{' '}
            It cannot see your grades, your finances, your health, your caring
            responsibilities or your immigration status unless you wrote them down.
          </li>
          <li>
            <strong className="text-white">It can reflect bias in its training data</strong>,
            including assumptions about who does which job. If a report seems to steer you by
            reference to something that should be irrelevant,{' '}
            <strong className="text-white">that is a fault and we want to hear about it.</strong>
          </li>
          <li>
            <strong className="text-white">It is not consistent.</strong> Ask twice and you
            will get two different reports. Neither is the &ldquo;real&rdquo; answer.
          </li>
          <li>
            <strong className="text-white">No human reads it before you do.</strong> The
            report goes from the model to your screen. Nobody here checks it, and no qualified
            careers adviser reviews or approves it.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="not" title="What this service is not">
        <ul className="ml-5 flex list-disc flex-col gap-2">
          <li>
            <strong className="text-white">Not professional careers advice or counselling.</strong>{' '}
            We are not a regulated careers service.
          </li>
          <li>
            <strong className="text-white">Not a psychometric test.</strong> The questionnaire
            is not validated, not normed against any population, and has no published
            reliability or validity data. It must not be used for recruitment, selection or
            admissions.
          </li>
          <li>
            <strong className="text-white">
              Not medical, psychological or mental health advice
            </strong>
            , and not a diagnosis of anything.
          </li>
          <li>
            <strong className="text-white">
              Not legal, financial, tax, immigration or admissions advice.
            </strong>{' '}
            Anything a report says about visas, loans, funding, entry requirements or
            professional registration must be checked against an official source.
          </li>
          <li>
            <strong className="text-white">Not a prediction and not a guarantee.</strong> No
            report promises you a job, a place, a salary, or a career you will enjoy.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="decides-nothing" title="Nothing here decides anything about you">
        <p>
          The service produces information for you to consider.{' '}
          <strong className="text-white">It does not decide</strong> whether you get a job, a
          place on a course, a loan or anything else, and it is not connected to any
          organisation that makes those decisions.
        </p>
        <p>
          Your scores and reports are{' '}
          <strong className="text-white">
            not shared with any university, employer, school or careers service.
          </strong>{' '}
          Nobody sees them unless you choose to show them.
        </p>
        <p>
          Because nothing here produces a legal or similarly significant effect on you, we do
          not consider Article 22 of the UK GDPR &mdash; the right not to be subject to a
          solely automated decision &mdash; to be engaged. We are showing you our reasoning
          rather than asking you to take it on trust, and our{' '}
          <a className="text-indigo-300 underline" href="/privacy#automated">
            Privacy Policy
          </a>{' '}
          sets it out more fully.
        </p>
      </LegalSection>

      <LegalSection id="human-review" title="Getting a human involved">
        <p>
          Whatever the strict legal position, you can always ask us to look at a result.{' '}
          <strong className="text-white">
            We offer this because it is right, not because we have concluded we must.
          </strong>
        </p>
        <ul className="ml-5 flex list-disc flex-col gap-2">
          <li>Ask us to explain the logic of the scoring model in plain English.</li>
          <li>Ask a person here to look at your report or scores and comment on it.</li>
          <li>Tell us you think a result is wrong or unfair, and have us review it.</li>
          <li>Ask us to delete a report you would rather did not exist.</li>
        </ul>
        <p>
          Email{' '}
          <a className="text-indigo-300 underline" href={`mailto:${CONTACT.privacy}`}>
            {CONTACT.privacy}
          </a>
          . We aim to reply within 3 working days and to complete a review within one month.
        </p>
      </LegalSection>

      <LegalSection id="distress" title="If your answers suggest you are struggling">
        <p>
          A questionnaire that asks what you have failed at and what you are afraid of will
          sometimes receive answers describing real distress. So that the service does not
          respond to that by cheerfully listing job clusters, your free-text answers are
          checked against a fixed list of phrases suggesting self-harm or suicidal thoughts.
        </p>
        <p>
          If one matches, support information is shown above your report and the model is
          instructed to write more carefully. Your report is{' '}
          <strong className="text-white">not blocked, delayed or changed</strong> in its
          career content &mdash; you asked for it and you are entitled to it.
        </p>
        <p className="font-medium text-white">What this is not:</p>
        <ul className="ml-5 flex list-disc flex-col gap-2">
          <li>
            It is a <strong className="text-white">keyword match, not an assessment</strong>.
            It will miss things and will sometimes fire on ordinary phrasing.
          </li>
          <li>
            <strong className="text-white">Nothing is stored.</strong> The result exists for
            one request and is then gone &mdash; not saved, not attached to your account, not
            visible to anyone.
          </li>
          <li>
            <strong className="text-white">Nobody is alerted.</strong> No human is notified,
            and we do not monitor individuals.
          </li>
          <li>
            It is <strong className="text-white">not a safety net</strong>. Please do not rely
            on it.
          </li>
        </ul>
        <div className="rounded-lg border border-indigo-400/30 bg-indigo-400/10 p-4">
          <p className="text-sm text-indigo-100">
            <strong className="font-semibold">If you are in danger right now, call 999.</strong>{' '}
            Samaritans are free, 24 hours a day, on <strong>116 123</strong>, or email
            jo@samaritans.org. Shout offers text support &mdash; text SHOUT to{' '}
            <strong>85258</strong>. If you are a student, your university or college will have
            a wellbeing service.
          </p>
        </div>
      </LegalSection>

      <LegalSection id="tell-us" title="Telling us when the AI gets it wrong">
        <p>
          <strong className="text-white">Please tell us.</strong> Email{' '}
          <a className="text-indigo-300 underline" href={`mailto:${CONTACT.support}`}>
            {CONTACT.support}
          </a>{' '}
          with what the report said and what was wrong with it.
        </p>
        <p>
          This is the single most useful thing you can do for the product. We cannot see your
          reports as a matter of routine, and a failure mode we do not know about is one we
          cannot fix. We particularly want to hear about invented facts stated confidently,
          advice that would be harmful to follow, anything that reads as biased or steering,
          and anything distressing.
        </p>
      </LegalSection>

      <LegalSection id="regulation" title="Where we stand with regulators">
        <p>
          <strong className="text-white">United Kingdom.</strong> There is no general AI
          statute in force. Our obligations come from data protection law, consumer law, and
          the ordinary law of negligence and misrepresentation. This notice is written to meet
          the transparency expectations in the ICO&rsquo;s guidance on AI and data protection.
        </p>
        <p>
          <strong className="text-white">Elsewhere.</strong> We are a UK business selling to
          individuals. If that changes, or if the EU AI Act is found to reach this product
          because its output is used in the EU, this page will change with it and we will say
          so.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="Changes">
        <p>
          If we change the AI provider, the model, or what we send it, we will update this
          notice and change the date at the top. If the change materially affects what the
          service does with your answers, we will email you.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
