import type { Metadata } from 'next';
import LegalPage, { LegalSection } from '@/components/LegalPage';
import { COMPANY, CONTACT, LAST_UPDATED } from '@/lib/legal';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The agreement between you and CareerBridge Way: what we provide, what we do not promise, and where you stand if something goes wrong.',
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated={LAST_UPDATED.terms}
      intro={
        <>
          <p>
            These terms are the agreement between you and {COMPANY.legalName} when you use{' '}
            {COMPANY.tradingName}. By creating an account you accept them.
          </p>
          <p>
            The two sections worth reading properly are{' '}
            <a className="text-indigo-300 underline" href="#what-this-is-not">
              what this service is not
            </a>{' '}
            and{' '}
            <a className="text-indigo-300 underline" href="#liability">
              our liability
            </a>
            . The rest is what you would expect.
          </p>
        </>
      }
    >
      <LegalSection id="who-we-are" title="1. Who you are contracting with">
        <p>
          {COMPANY.tradingName} is a trading name of {COMPANY.legalName}, registered in{' '}
          {COMPANY.jurisdiction} under number {COMPANY.companyNumber}, registered office{' '}
          {COMPANY.address}. Contact us at{' '}
          <a className="text-indigo-300 underline" href={`mailto:${CONTACT.support}`}>
            {CONTACT.support}
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection id="eligibility" title="2. Who can use it">
        <p>
          You must be at least 16 years old to create an account. If you are under 18, you
          should go through your results with a parent, guardian, teacher, or careers
          adviser rather than relying on them alone.
        </p>
        <p>
          You are responsible for what happens under your account, so keep your sign-in
          details to yourself. Tell us straight away if you think someone else has got into
          your account.
        </p>
      </LegalSection>

      <LegalSection id="what-we-provide" title="3. What we provide">
        <p>
          A questionnaire, a scoring model that groups your answers into career clusters,
          and an AI-generated written report based on those answers. Paid plans add
          attempts and a follow-up questionnaire that produces a more detailed roadmap.
        </p>
        <p>
          We may change, improve, or retire parts of the service. If we retire something you
          have already paid for and cannot deliver it, we will refund you for that part.
        </p>
      </LegalSection>

      <LegalSection id="what-this-is-not" title="4. What this service is not">
        <p>
          This matters more here than on most websites, so it is in plain words rather than
          buried in capital letters.
        </p>
        <ul className="ml-5 flex list-disc flex-col gap-2">
          <li>
            <strong className="text-white">
              It is not professional careers advice or counselling.
            </strong>{' '}
            We are not a regulated careers service and your report is not produced or
            reviewed by a qualified careers adviser.
          </li>
          <li>
            <strong className="text-white">
              It is not a psychological or psychometric assessment.
            </strong>{' '}
            The questionnaire is not a clinically validated instrument and it does not
            diagnose anything about you.
          </li>
          <li>
            <strong className="text-white">It is not medical or mental health advice.</strong>{' '}
            If you are struggling, please talk to your GP or one of the support services we
            link to. Nothing here is a substitute for that.
          </li>
          <li>
            <strong className="text-white">It is not a guarantee of any outcome.</strong> We
            do not promise that following the report will get you a job, a place on a
            course, a salary, or a career you enjoy.
          </li>
          <li>
            <strong className="text-white">It is generated by AI, and AI gets things wrong.</strong>{' '}
            Reports can contain inaccurate, outdated, or simply mistaken statements about
            jobs, qualifications, and pay. Check anything important before you act on it.
          </li>
        </ul>
        <p>
          Every decision about your education, your work, and your future stays yours. Treat
          the report as one input among several &mdash; alongside people who actually know
          you.
        </p>
      </LegalSection>

      <LegalSection id="payment" title="5. Payment">
        <p>
          Prices are shown before you pay and are charged in the currency displayed at
          checkout. Payment is handled by Stripe; we never see your card details.
        </p>
        <p>
          What each product gives you is stated on the checkout page before you pay.
          Purchases are one-off &mdash; we do not run subscriptions, nothing renews
          automatically, and we will never charge you again without you choosing to buy
          something.
        </p>
        <p>
          Your right to cancel and get a refund is set out in our{' '}
          <a className="text-indigo-300 underline" href="/refunds">
            Refund and Cancellation Policy
          </a>
          , which forms part of these terms.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" title="6. How you may use it">
        <p>Please do not:</p>
        <ul className="ml-5 flex list-disc flex-col gap-2">
          <li>Try to break, overload, or get unauthorised access to the service</li>
          <li>Use automated tools to submit assessments or generate reports in bulk</li>
          <li>Resell your reports, or present them as your own product</li>
          <li>Submit someone else&rsquo;s personal information as your answers</li>
          <li>
            Try to make the AI produce content unrelated to careers, or attempt to extract
            our prompts or other users&rsquo; data
          </li>
        </ul>
        <p>
          We may suspend or close an account that does these things. Where we reasonably can,
          we will tell you why first.
        </p>
      </LegalSection>

      <LegalSection id="your-content" title="7. Your answers and your report">
        <p>
          Your answers remain yours. You give us permission to process them to run the
          assessment and produce your report, as described in our{' '}
          <a className="text-indigo-300 underline" href="/privacy">
            Privacy Policy
          </a>
          .
        </p>
        <p>
          Your report is yours to use for your own purposes. The questionnaire, the scoring
          model, and the site itself remain ours.
        </p>
      </LegalSection>

      <LegalSection id="liability" title="8. Our liability to you">
        <p>
          Nothing in these terms limits our liability for death or personal injury caused by
          our negligence, for fraud, or for anything else that cannot be limited by law.
          Nothing here affects your statutory rights as a consumer under the Consumer Rights
          Act 2015.
        </p>
        <p>Subject to that:</p>
        <ul className="ml-5 flex list-disc flex-col gap-2">
          <li>
            <strong className="text-white">
              We are not liable for decisions you make based on a report.
            </strong>{' '}
            That includes choosing or leaving a course, job, or career path, and any loss of
            income, opportunity, or time that follows.
          </li>
          <li>
            We are not liable for indirect or consequential loss, lost profits, lost
            opportunity, or loss of data.
          </li>
          <li>
            <strong className="text-white">
              Our total liability to you is capped at the amount you have paid us in the 12
              months before the claim
            </strong>
            , or £100 if you have paid us nothing.
          </li>
          <li>
            We do not promise the service will be uninterrupted or error-free. It depends on
            third parties &mdash; hosting, payments, and an AI provider &mdash; and any of
            them can have a bad day.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="indemnity" title="9. Your liability to us">
        <p>
          If you use the service in a way these terms forbid &mdash; breaking the acceptable
          use rules, submitting someone else&rsquo;s personal data, or infringing someone
          else&rsquo;s rights &mdash; and that causes a third party to bring a claim against
          us, you agree to cover the reasonable costs and damages we incur as a result.
        </p>
        <p>
          This does not apply to anything arising from our own breach of these terms or our
          own negligence, and it does not apply to ordinary use of the service.
        </p>
      </LegalSection>

      <LegalSection id="termination" title="10. Ending the agreement">
        <p>
          You can close your account whenever you like, from your account settings. Deleting
          your account removes your data as described in the Privacy Policy, and unused
          attempts are lost when you do &mdash; so use or claim a refund on them first.
        </p>
        <p>
          We may end this agreement if you seriously or repeatedly break these terms, or if
          we stop operating the service. If we close your account for our own reasons rather
          than yours, we will refund anything you have paid for and not received.
        </p>
      </LegalSection>

      <LegalSection id="law" title="11. Governing law">
        <p>
          These terms and any dispute arising from them are governed by the law of{' '}
          {COMPANY.jurisdiction}, and the courts of {COMPANY.jurisdiction} have exclusive
          jurisdiction.
        </p>
        <p>
          If you are a consumer living elsewhere in the UK or in the EU, this does not take
          away the protection of the mandatory consumer laws of the country you live in, and
          you may be able to bring proceedings there.
        </p>
      </LegalSection>

      <LegalSection id="general" title="12. Odds and ends">
        <p>
          If a court finds part of these terms unenforceable, the rest stays in force. If we
          do not enforce something straight away, we have not given up the right to enforce
          it later. These terms are between you and us; nobody else can enforce them.
        </p>
        <p>
          We may update these terms. If a change materially affects your rights, we will
          email you before it takes effect and the date at the top of this page will change.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
